---
- name: Ensure Management Domain is configured for Automation
  cisco.ios.ios_config:
    lines:
      - ip domain-name campus.local

- name: Save configuration if modified
  cisco.ios.ios_config:
    save_when: modified