---
# Distribution switch for DMME.
vlans:
  - vlan_id: 30
    name: VLAN_DMME
  - vlan_id: 99
    name: MGMT
  - vlan_id: 100
    name: NATIVE

trunk_interfaces:
  - interface: FastEthernet1/0
    description: "Uplink to SW-CORE"
  - interface: FastEthernet1/1
    description: "Downlink to SW-A-DMME"
