---
- name: Deploy Base Campus Network Configuration
  hosts: all
  gather_facts: false
  
  # Load your data
  vars_files:
    - vars/vlans.yml

  tasks:
    - name: Ensure all Department VLANs exist
      cisco.ios.ios_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
        state: merged
      loop: "{{ vlans }}"